### ISSUE TITLE
onResize target issues

### ISSUE THREAD

**Issue by faassen** [MonsantoCo/column-resizer#1]
The documentation says:

> If a callback function is supplied it will be fired when the user has ended dragging a column anchor 
> altering the previous table layout. The callback function can obtain a reference to the updated table 
> through the currentTarget attribute of the event retrieved by parameters

The currentTarget however points to the HTML document. The target is the grip itself.

What I'm looking for is a way to track what widths were used for the columns so I can store it, so that when the table is shown again it's shown with the same widths.

**Comment by faassen** [comment]
Though I suspect I can work around this if I create a React component that handles this -- in that case I already have a reference to the table itself anyway.

**Comment by jglynn43** [comment]
There's no way to do that right now. However, the column widths are stored in session storage on each redraw. Possibly capture the width then and extend options object with initial widths?

**Comment by jglynn43** [comment]
This is in v1.0.2
