### ISSUE TITLE
td Drag for Vertical table

### ISSUE THREAD

**Issue by pradeepgill007** [MonsantoCo/column-resizer#15]
**Need to add support for td Vertical table.**
Need to increase the height of the td if we have Vertical table.

**HTML**
```
<table width="100%" border="1" height="100%" id="somethingUnique">
  <tr>
    <th>This th should be dragable by height </th>
    <td>Bill Gates</td>
    <td>Bill Gates</td>
  </tr>
  <tr>
    <th>This th should be dragable by height</th>
    <td>555 77 854</td>
    <td>555 77 854</td>
  </tr>
  <tr>
    <th>This th should be dragable by height</th>
    <td>555 77 855</td>
    <td>555 77 855</td>
  </tr>
</table>
```
<table width="100%" border="1" height="100%" id="somethingUnique">
  <tr>
    <th>This th should be dragable by height </th>
    <td>Bill Gates</td>
    <td>Bill Gates</td>
  </tr>
  <tr>
    <th>This th should be dragable by height</th>
    <td>555 77 854</td>
    <td>555 77 854</td>
  </tr>
  <tr>
    <th>This th should be dragable by height</th>
    <td>555 77 855</td>
    <td>555 77 855</td>
  </tr>
</table>

**Comment by jglynn43** [comment]
This is outside the scope of this project.
