### ISSUE TITLE
Set th Width always in %

### ISSUE THREAD

**Issue by pradeepgill007** [MonsantoCo/column-resizer#16]
How can I set the width of `td` in percentage always after enableResize?

<img width="1440" alt="Screenshot 2019-08-06 at 4 17 52 PM" src="https://user-images.githubusercontent.com/15011663/62534110-f7cb1500-b865-11e9-8fd1-7c1d5187258a.png">

**Comment by pradeepgill007** [comment]
@jglynn43 any update on this give me an idea as I am in mid-development.

**Comment by jglynn43** [comment]
You can not set the widths as a percentage. If you set `resizeMode` to `fit`, then the column widths will be in percent when the entire table is resized. For example, when the browser window is resized.

**Comment by pradeepgill007** [comment]
@jglynn43 thank you for your response.
I don't have the window resize event. I have a custom resizable div and i want to convert the `px` th width into `%`.

![table](https://user-images.githubusercontent.com/15011663/62607096-20611680-b91b-11e9-8135-78f73b17f42e.gif)

Can you give me any event on which I can calculate and convert the width to `%` just like it is happening in sample Percentage-based layouts examples?

**Comment by jglynn43** [comment]
That's the only event handled other than when dragging. What "sample Percentage-based layouts example" are you referring to?

**Comment by pradeepgill007** [comment]
I am referring to this `http://bacubacu.com/colresizable/`.

**Comment by jglynn43** [comment]
That particular example uses jQuery. This project does not and that is why that particular example is not in this project. If you want help with this, you should ask the creator of that project, Mr. Lauroba.
