### ISSUE TITLE
Overflowing table header is not hidden

### ISSUE THREAD

**Issue by neomobil** [MonsantoCo/column-resizer#18]
The overflowing table header is not hidden

**To Reproduce**
Initialize a table and resize the header smaller then the header text
Options:
        liveDrag: true,
        gripInnerHtml:` '<div class="rangeGrip"></div>',`
        minWidth: 25,
        headerOnly: true,
        serialize: true,
        resizeMode: 'fit'

**Expected behavior**
Oveflowing header text should be hidden

**Screenshots**
![screenshot-localhost_8080-2019 11 30-22_38_30](https://user-images.githubusercontent.com/187594/69906326-3c089500-13c2-11ea-9c43-e2c044dfc195.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Chrome

**Smartphone (please complete the following information):**
 - 78.0.3904.108 (Official Build) (64-bit)

**Additional context**
In the init method should be changed the style part from
`.grip-resizable > tbody > tr > th{overflow:hidden}`
to
`.grip-resizable > thead > tr > th{overflow:hidden}`

**Comment by jglynn43** [comment]
I'm only able to reproduce when I make the changes you suggest. Without changing, it does not exhibit the behavior described.
