### ISSUE TITLE
Add an option to reset columns to their initial widths

### ISSUE THREAD

**Issue by omers4** [MonsantoCo/column-resizer#19]
**Is your feature request related to a problem? Please describe.**
Hi, I use your package and would like to understand how to reset the columns to their initial size (which means, erase the localStorage property and init table columns)

**Describe the solution you'd like**
I would expect that this.resizer.reset() will change the columns to their original widths.

**Describe alternatives you've considered**
The way I tried to do it is by calling this.resizer.reset() but that didn't work,
So what I'm doing now and is kind of horrible, is to save the initial widths in my react state, and when a user clicks a button, I call reset() with these widths. It causes problems in case the window size was changed etc.

Thank you

**Comment by huraji** [comment]
I see there is an option like `widths: []` but that doesn't work either. I'm not sure if there is still anybody maintaining this.

**Comment by jglynn43** [comment]
Hello,

So, if you have the initial widths for each column, you can create the resizer using the options with widths set as an array of numbers in it. Some examples of using options when creating are here: https://github.com/MonsantoCo/column-resizer/blob/master/samples/colResizable.Demo/demo.html

To get back to the original widths *and* clear the local session store, two steps are needed. First clear the store by calling reset with the `disable` option like this.resizer.reset({disable: true}). Calls to `reset` return the previous options object it was called with so you can call `reset` again with that or just use the one you originally created the resizer with. A one liner would be in your case 

`this.reziser.reset(this.resizer.reset({disable: true}))`

If you don't need the local session storage at all, create your resizer with the `serialize` option set to `false`. In that case you will have to call reset with the original options object you created the resizer with.
