### ISSUE TITLE
Add typescript definitions

### ISSUE THREAD

**Issue by kspearrin** [MonsantoCo/column-resizer#2]
Right now we have to use it like this:

```
const ColumnResizer = require('column-resizer');
const resizer = new ColumnResizer.default(document.getElementById('mytable'), {});
```

Which isn't ideal. It would be great if there were TS definitions so we could import it like normal. Thanks!

**Comment by Mikkou** [comment]
Actually question

**Comment by jglynn43** [comment]
Thanks for your interest! I don't really know anything about TypeScript and I've been up to my neck in Scala on another project for a while now. If it can be added to this project without breaking its charter as plain vanilla JS, feel free to submit a pull request.

**Comment by neomobil** [comment]
It's also possible to import it.
`import ColumnResizer from column-resizer'
`
