### ISSUE TITLE
ES5 Version

### ISSUE THREAD

**Issue by pirolito** [MonsantoCo/column-resizer#25]
Hello,

i was trying to use this in an angular 9 project, but i can't make it work in IE11 since this is written in ES6 and IE11 don't support the arrow functions.

Can this could be written in ES5?

**Comment by jglynn43** [comment]
No, this is a vanilla ES6 project. If you need an earlier version of the language, you should fork this project and update the `.babelrc` file with the specific `preset-env` properties you need.
