### ISSUE TITLE
need help how to use in react app

### ISSUE THREAD

**Issue by kamaldlk** [MonsantoCo/column-resizer#3]
need help how to use in react app, Please give me codepen or codesandbox

**Comment by kamaldlk** [comment]
https://codesandbox.io/s/93xnrq8l24
check this one

**Comment by jglynn43** [comment]
I made a few changes to get it working, just adding an id and changing the selector to match. Also deleted the behavior property from the css. See https://codesandbox.io/s/jpl35qkxxw

**Comment by kamaldlk** [comment]
@jglynn43  Thank you so much :)
