### ISSUE TITLE
need help getting columns width information 

### ISSUE THREAD

**Issue by kamaldlk** [MonsantoCo/column-resizer#6]
import React, { Component } from 'react';
import ReactDOM from "react-dom";
import PropTypes from 'prop-types';
import ColumnResizer from "./column.resize";
import styles from '../css/datasheet.css';
import HeaderRenderer from './headerrenderer';

class DataSheetMainRenderer extends Component {
  constructor(props) {
    super(props);
    this.state = {};
  }

  componentDidMount() {
    const resizer = new ColumnResizer(document.getElementById("mytable"), {
      liveDrag: true,
      resizeMode: 'overflow',
      minWidth: 150,
      headerOnly: true,
      flush: true,
      disabledColumns: [0, this.props.viewForm ? 1 : null]
    });
    if (this.props.resizable) {
      this.enableResize();
    }
  }
  componentWillUpdate() {
    console.log('resizersdsdsds');
    if (this.props.resizable) {
      this.disableResize();
    }
  }
  componentDidUpdate() {
    console.log('resizersdsdsd2112s');
    if (this.props.resizable) {
      this.enableResize();
    }
  }
  componentWillUnmount() {
    if (this.props.resizable) {
      this.disableResize();
    }
  }

  enableResize() {
    const normalRemote = ReactDOM.findDOMNode(this).querySelector(
      `#${this.bodyId}`
    );
    const options = this.props.resizerOptions;
    options.remoteTable = normalRemote;
    if (!this.resizer) {
      this.resizer = new ColumnResizer(
        ReactDOM.findDOMNode(this).querySelector(`#${this.headerId}`),
        options
      );
      console.log('this.resizer', this.resizer);
    } else {
      this.resizer.reset(options);
      console.log('this.resizer', this.resizer);
    }
  }

  disableResize() {
    if (this.resizer) {
      console.log('this.resizer', this.resizer);
      // This will return the current state of the
      // options including column widths.
      // These widths can be saved so the table
      // can be initialized with them.
      this.resizer.reset({ disable: true });
    }
  }

  render() {
    const { className, columns, viewForm, checkboxIndex } = this.props;
    return(
      <table className={className} id="mytable">
        {/* <colgroup>
          <col width= {'40px'}/>
          {viewForm && <col width= {'40px'}/>}
          {
            columns.map((col, index) => (
              <col key={col.Id} width= {(col.Width || 150) + 'px'}/>
            ))
          }
        </colgroup> */}
        <thead className={`${styles.dataHeader}`}>
          <HeaderRenderer {...this.props}/>
        </thead>
        <tbody className={`${styles.dataBody}`}>
          {this.props.children}
        </tbody>
      </table>
    );
  }
}

DataSheetMainRenderer.propTypes = {
  children: PropTypes.oneOfType([
    PropTypes.element,
    PropTypes.array
  ]),
  className: PropTypes.PropTypes.string,
  selected: PropTypes.array,
  onSelectAllChanged: PropTypes.func,
  columns: PropTypes.array.isRequired,
  selections: PropTypes.array,
  onColumnDrop: PropTypes.func,
  sort: PropTypes.array,
  checkboxIndex: PropTypes.bool,
  viewForm: PropTypes.bool,
  handleSort: PropTypes.func,
  rowsCount: PropTypes.number,
  resizable: PropTypes.bool,
  resizerOptions: PropTypes.object
};

export default DataSheetMainRenderer;
Where i will recive width information

**Comment by kamaldlk** [comment]
@jglynn43  any update on this give me some idea

**Comment by jglynn43** [comment]
I have updated the API documentation in v1.1.0 to give a better idea of where to get this information.

**Comment by kamaldlk** [comment]
Thanks @jglynn43
