### ISSUE TITLE
IE11 compatibility. Element.matches()

### ISSUE THREAD

**Issue by ttcremers** [MonsantoCo/column-resizer#7]
**Describe the bug**

Column resize init throws an exception on IE11 without matches() polyfill.   

> SCRIPT438: Object doesn't support property or method 'matches'

**Desktop (please complete the following information):**
 - OS: Windows 7/8/10
 - Browser: Internet Explorer
 - Version: 11

This issue would be easily fixed by adding this 3 line polyfill:

```
if (!Element.prototype.matches) {
    Element.prototype.matches = Element.prototype.msMatchesSelector;
}
```
Is this fix considered to be in the scope of the project or is it left to the dev to load/include the polyfill?

Thanks

**Comment by jglynn43** [comment]
Released v1.1.2 to address the issue.
