### ISSUE TITLE
What is HeaderID?

### ISSUE THREAD

**Issue by jeffkillian** [MonsantoCo/column-resizer#8]
In the readme, it mentions we should use `headerId`, but we never specify that anywhere. Which tag do we give the `headerId` attribute to?

**Comment by joeyparis** [comment]
I think the variable name `headerId` used in the example is misleading. I got this working by referencing the DOM node of the table element, not the header row specifically.

**Comment by jglynn43** [comment]
Hi, I'm sorry the documentation is confusing. I'll fix that in the next release. The `headerId` there is actually the DOM id of the table element. What is going on in this example is actually two tables with a 'header' table controlling the columns of a 'body' table. With this, you could say have a table at the top (or anywhere) on the page, some other elements, and then a different data table. As long as the columns count is the same, one table can control the columns of both.
